<?php

namespace VientoSur\App\AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AirlinesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirlinesRepository extends EntityRepository
{
    public function findAirlinesIn($codes)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('ai')
            ->from('VientoSurAppAppBundle:Airlines:Airlines', 'ai')
            ->where($qb->expr()->in('ai.id', $codes))
        ;

        return $qb->getQuery()->getResult();
    }
}
