<?php
/**
 * Created by PhpStorm.
 * User: David
 * Date: 31/3/2017
 * Time: 11:30 AM
 */

namespace VientoSur\App\AppBundle\Utils;


class Bank
{
    private $banks = [
        'RI' => 'Ripley',
        'ARP' => 'Aerolineas Plus',
        'AME' => 'American Express',
        'AMX' => 'AMERICAN EXPRESS AMEX',
        'AXC' => 'American Express Corporate',
        'BBVAF' => 'Banco Francés',
        'CDC' => 'Banco Credicoop',
        'COM' => 'Banco Comafi',
        'FRN' => 'Banco Francés',
        'GLC' => 'Banco Galicia',
        'HIP' => 'Banco Hipotecario',
        'HSBC' => 'Banco HSBC',
        'ITU' => 'Banco Itaú',
        'MAC' => 'Banco Macro',
        'NAC' => 'Banco Nación',
        'NAR' => 'Naranja',
        'PAT' => 'Banco Patagonia',
        'PRO' => 'Banco Provincia',
        'RIO' => 'Banco Santander Rio',
        'AZU' => 'Banco Industrial',
        'BERSA' => 'Banco Entre Ríos',
        'BLP' => 'Banco de la Pampa',
        'BSE' => 'Santiago del Estero',
        'CHA' => 'Nuevo Banco del Chaco',
        'CHU' => 'Banco del Chubut',
        'CIT' => 'Citibank',
        'CIU' => 'Banco Ciudad',
        'CMR' => 'Falabella',
        'COR' => 'Cordobesa',
        'CS' => 'Cencosud',
        'ICBC' => 'Banco ICBC',
        'ITM' => 'Itaú Movistar',
        'NAT' => 'Nativa',
        'NBSF' => 'Banco Santa Fe',
        'NEU' => 'Banco Provincia de Neuquén',
        'PROMO' => '',
        'ROS' => 'Banco Municipal de Rosario',
        'SCR' => 'Banco Santa Cruz',
        'SJU' => 'Banco San Juan',
        'SUP' => 'Banco Supervielle',
        'SUPB' => 'Black Supervielle',
        'TUC' => 'Banco del Tucumán',
        'FOR' => 'Banco Formosad',
        'DEBAR' => 'Débito Argentina',
        'BCO' => 'Banco de Corrientes',
        'BTDF' => 'Banco Tierra del Fuego',
        'CRE' => 'Credilogros',
        'GRL' => 'todos los Bancos',
        'NBLR' => 'Banco La Rioja',
        'PVC' => 'Provencred',
        'SAENZ' => 'Banco Saénz',
        'SHO' => 'Tarjeta shopping',
        'TFPL' => 'Tierra del Fuego Platinum',
        'BRA' => 'Bradesco',
        'PLA' => 'Platinum',
        'BB' => 'Banco do Brasil',
        'CITI' => 'Citibank',
        'ORIG' => 'Banco Original de Brasil',
        'SRIO' => 'Santander',
        'BCH' => 'Banco de Chile',
        'CMT' => 'Banco Credomatic',
        'CORP' => 'Banco Corpbanca',
        'STR' => 'Banco Santander',
        'BBVA' => 'Banco BBVA',
        'BCHI' => 'Banco CrediChile',
        'BCI' => 'Banco Bci',
        'BEST' => 'Banco Estado',
        'CSCL' => 'Tarjeta Cencosud',
        'ITA' => 'Itaú Chile',
        'SCB' => 'ScotiaBank',
        'SEC' => 'Banco Security',
        'TBANC' => 'Banco TBANC',
        'BICE' => 'Banco Bice',
        'BBVACO' => 'Banco BBVA',
        'BOG' => 'Banco de Bogotá',
        'CITCO' => 'Citibank',
        'COLPA' => 'Colpatria',
        'DAV' => 'Davivienda',
        'HELM' => 'HelmBank',
        'SOL' => 'Banco Solidario',
        'GUA' => 'Banco de Guayaquil',
        'AUS' => 'Banco del Austro',
        'BOL' => 'Banco Bolivariano',
        'CEN' => 'Banco Centro Mundo',
        'INT' => 'Banco Internacional',
        'INTER' => 'Banco Internacional',
        'MPI' => 'Mutualista Pichincha',
        'PAC' => 'PacifiCard',
        'PIC' => 'Banco Pichincha',
        'PRB' => 'Banco Produbanco',
        'AMA' => 'Banco Amazonas',
        'LOJ' => 'Banco de Loja',
        'MAN' => 'Banco de Machala',
        'MUT' => 'Mutualista del Azuay',
        'PRM' => 'Banco Promerica',
        'RUM' => 'Banco Rumiñahui',
        'TER' => 'Banco Territorial',
        'UNI' => 'Banco Unibanco',
        'AFIRM' => 'Banco Banco Afirme',
        'BAJIO' => 'Banco del Bajio',
        'BANJE' => 'Banco Banjercito',
        'BANOR' => 'Banco Banorte',
        'BANRE' => 'Banco Banregio',
        'BANXE' => 'Banco Banorte-Ixe',
        'BBVAB' => 'Banco BBVA Bancomer',
        'BN' => 'Banco Banorte',
        'BX' => 'Banco Banamex',
        'FAMSA' => 'Banco Famsa',
        'HSB' => 'Banco HSBC',
        'INBUR' => 'Banco Inbursa',
        'INVEX' => 'Banco Invex',
        'ITAU' => 'Banco Itau',
        'IXE' => 'Banco IXE',
        'MIFEL' => 'Banco Mifel',
        'SAN' => 'Banco Santander',
        'SB' => 'Banco ScotiaBank',
        'LIV' => 'Banco Liverpool',
        'BCP' => 'Banco BCP',
        'INB' => 'Banco Interbank',
        'BBVAC' => 'BBVA Continental',
        'CSPE' => 'Cencosud',
        'BBF' => 'Banco BanBif',
        'CMRP' => 'Falabella',
        'GNBPE' => 'Banco GNB',
        'OH' => 'Tarjeta Oh!',
        'PE' => 'PagoEfectivo',
        'generic' => 'Todos',
        '' => '',
        'POL' => 'La Polar',
        'CAGRL' => 'General',
        'COL' => 'Columbia',
        'CHIC' => 'Comafi Chicas',
        'SFJO' => 'Banco Santa Fe',
        'ITAUB' => 'Itaucard Latam',
        'SANBR' => 'Santander',
        'LIDER' => 'Lider',
        'ABCVI' => 'ABC',
        'BCOL' => 'Bancolombia',
        'ITAUCO' => 'Itaú',
        'CORPC' => 'CorpBanca',
        'MCH' => 'Banco de Machala',
        'TIT' => 'Titanium',
        'CRES' => 'Banco CrediScotia',
        'INF' => 'Infinite',
        'SBP' => 'ScotiaBank'
    ];


    private $banksSimple = [
        'RI',
        'ARP',
        'AME',
        'AMX',
        'AXC',
        'BBVAF',
        'CDC',
        'COM',
        'FRN',
        'GLC',
        'HIP',
        'HSBC',
        'ITU',
        'MAC',
        'NAC',
        'NAR',
        'PAT',
        'PRO',
        'RIO',
        'AZU',
        'BERSA',
        'BLP',
        'BSE',
        'CHA',
        'CHU',
        'CIT',
        'CIU',
        'CMR',
        'COR',
        'CS',
        'ICBC',
        'ITM',
        'NAT',
        'NBSF',
        'NEU',
        'PROMO',
        'ROS',
        'SCR',
        'SJU',
        'SUP',
        'SUPB',
        'TUC',
        'FOR',
        'DEBAR',
        'BCO',
        'BTDF',
        'CRE',
        'GRL',
        'NBLR',
        'PVC',
        'SAENZ',
        'SHO',
        'TFPL',
        'BRA',
        'PLA',
        'BB',
        'CITI',
        'ORIG',
        'SRIO',
        'BCH',
        'CMT',
        'CORP',
        'STR',
        'BBVA',
        'BCHI',
        'BCI',
        'BEST',
        'CSCL',
        'ITA',
        'SCB',
        'SEC',
        'TBANC',
        'BICE',
        'BBVACO',
        'BOG',
        'CITCO',
        'COLPA',
        'DAV',
        'HELM',
        'SOL',
        'GUA',
        'AUS',
        'BOL',
        'CEN',
        'INT',
        'INTER',
        'MPI',
        'PAC',
        'PIC',
        'PRB',
        'AMA',
        'LOJ',
        'MAN',
        'MUT',
        'PRM',
        'RUM',
        'TER',
        'UNI',
        'AFIRM',
        'BAJIO',
        'BANJE',
        'BANOR',
        'BANRE',
        'BANXE',
        'BBVAB',
        'BN',
        'BX',
        'FAMSA',
        'HSB',
        'INBUR',
        'INVEX',
        'ITAU',
        'IXE',
        'MIFEL',
        'SAN',
        'SB',
        'LIV',
        'BCP',
        'INB',
        'BBVAC',
        'CSPE',
        'BBF',
        'CMRP',
        'GNBPE',
        'OH',
        'PE',
        'generic',
        '',
        'POL'
    ];

    public function getBanksSimple()
    {
        return $this->banksSimple;
    }

    public function getBanks()
    {
        return $this->banks;
    }
}