<?php

namespace VientoSur\App\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ResultLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultLogRepository extends EntityRepository
{
}
